Database/Flask project/my_app/models/model.py
from flask import Blueprint, render_template
from my_app import db

bp = Blueprint('model', __name__)



class Item(db.Model):
    __table_args__ = ({"schema" : "shopping"})
    __table__ = db.Model.metadata.tables['item']
    

    def __repr__(self):
        return str(self.index)


class Sales(db.Model):
    __table__ = db.Model.metadata.tables['sales']

    def __repr__(self):
        return str(self.index)


class Rating(db.Model):
    __table__ = db.Model.metadata.tables['rating']

    def __repr__(self):
        return str(self.index)


class Users(db.Model):
    __table__ = db.Model.metadata.tables['user']

    def __repr__(self):
        return str(self.id)


# class Ingr(db.Model):
#     __table__ = db.Model.metadata.tables['ingredients_csv']

#     def __repr__(self):
#         return str(self.id)

Database/Flask project/my_app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired

from wtforms import StringField, TextAreaField, PasswordField
from wtforms.fields.html5 import EmailField, IntegerField
from wtforms.validators import DataRequired, Length, EqualTo, Email


class UserCreateForm(FlaskForm):
    username = StringField('사용자이름', validators=[DataRequired(), Length(min=3, max=25)])
    password1 = PasswordField('비밀번호', validators=[
    DataRequired(), EqualTo('password2', '비밀번호가 일치하지 않습니다')])
    password2 = PasswordField('비밀번호확인', validators=[DataRequired()])

class UserLoginForm(FlaskForm):
    username = StringField('User Name', validators=[DataRequired(), Length(min=3, max=25)])
    password = PasswordField('Password', validators=[DataRequired()])

class ChangePassword(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired("New Password")])
    

Database/Flask project/my_app/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
# from sqlalchemy.ext.automap import automap_base




app = Flask(__name__)
db = SQLAlchemy(app)

app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://root:wjdtjrdl1130!!@localhost:3306/shopping'
app.config['SECRET_KEY'] = "key"

with app.app_context():
    db.init_app(app)
    db.Model.metadata.reflect(db.engine)



from my_app.routes import (main_route,user_routes)
from my_app.models import model

app.register_blueprint(main_route.bp)
app.register_blueprint(user_routes.bp)
app.register_blueprint(model.bp)


    




if __name__ == '__main__':
    # app = create_app()
    app.run(debug=True)

Database/Flask project/my_app/routes/main_route.py
from flask import Blueprint, render_template, request, session, g, url_for
from werkzeug.utils import redirect
from my_app import db
from my_app.models.model import item, sales, rating

bp = Blueprint('main', __name__)

@bp.route('/')


def main():
    #user_name = session.get('user_name')
    #test = db.session.query(item.title_orig).one()



    #return render_template('index.html'/, test = test)
    return render_template('index.html')

Database/Flask project/my_app/routes/user_routes.py
from os import error
from flask import Blueprint, render_template, url_for, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from my_app import db

from my_app.forms import ChangePassword, UserCreateForm
from my_app.models.model import Users
# from my_app.models.model import Ingr, Pp_rp, In_rp, Raw_rp, Review, Users

from my_app.forms import UserCreateForm, UserLoginForm

import functools

bp = Blueprint('user', __name__, )

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = Users.query.filter_by(username=form.username.data).first()
        if not user:
            user = Users(username = form.username.data,
                        password = generate_password_hash(form.password1.data),
                        user_id = form.username.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.main'))
        else:
            flash('User already existing')
    return render_template('signup.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = Users.query.filter_by(username=form.username.data).first()
        if not user:
            error = "User does not exist"
        elif not check_password_hash(user.password, form.password.data):
            error = "Wrong password"
        if error is None:
            session.clear()
            session['user_name'] = user.username
            session['logged_in'] = True
            g.user = user
            return redirect(url_for('main.main')) 
        flash(error)
    return render_template('login.html', form=form)


@bp.before_app_request
def load_logged_in_user():
    user_name = session.get('user_name')

    if user_name == None:
        g.user = None
    else:
        g.user = db.session.query(Users).filter_by(username = user_name).first()
        # g.user = Users.query.get(user_name)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.main'))  




# breakpoint()

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view


@bp.route('/my_page', methods=('GET', 'POST'))
def mypage():
    form = ChangePassword()

    if request.method == 'POST' and form.validate_on_submit():
        user = Users.query.filter_by(username = g.user.username).first()
        if g.user != user:
            flash('no authority')
            return redirect(url_for('user.mypage'))
    
        else:
            user.password = generate_password_hash(form.password.data)
            db.session.commit()
            render_template('my_page.html', form=form)

    return render_template('my_page.html', form=form)


@bp.route('/modify/<user_id>', methods=('GET', 'POST'))
@login_required
def modify(user_id):
    form = ChangePassword()

    user = Users.query.filter_by(username = user_id).first()
    
    if g.user != user:
        flash('no authority')
        return redirect(url_for('user.mypage'))
    
    else:
        user.password = generate_password_hash(form.password.data)
        db.session.commit()
        render_template('my_page.html', form=form)


@bp.route('/delete/<user_id>')
@login_required
def delete(user_id):
    user = Users.query.filter_by(username = user_id).first()
    if g.user != user:
        flash('no authority')
        return redirect(url_for('user.mypage'))
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('main.main'))

Database/Flask project/my_app/templates/form_errors.html
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

Database/Flask project/my_app/templates/index.html
<html>
    <head>
        <title>
        Index Page
        </title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main_style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main_bootstrap.css') }}">

    </head>


    <body>
        {% include "navbar.html" %}
        
        <div class='title'>
          <h1 style="font-size:100px; text-align:center; margin-top:50px; color:white;">Code Store</h1>
        </div>
        <br>
        <br>
        <br>
        <br>

        <form method="get" action="{{ url_for('main.search', name='kw') }}">
            <div class="input-group" style='font-size: 50px;'>
              <input type="text" class="form-control kw" name="kw" id="kw" value="{{kw or '' }}" placeholder="Enter search value">
              <input type="submit" class="btn btn-primary" style="width:120px;background-color: maroon; border:none; cursor:pointer;" value="Search">
            </div>  
          </form>


    </body>
</html>

Database/Flask project/my_app/templates/login.html
<html>
    <head>
    <title>
      Index Page
    </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_bootstrap.css') }}">

  </head>
    </head>
    <body>
        {% include "navbar.html" %}
        <div class="jumbotron_login">
            <h1 style="font-size:50px; text-align:center; margin-top:50px; color:white;">Log In</h1>
            <form method="post" class="post-form">
                {{ form.csrf_token }}
                {% include "form_errors.html" %}
                <div class="form-group">
                    <label for="username">User Name&nbsp;&nbsp;</label>
                    <input type="text" class="form-control" name="username" id="username"
                        value="{{ form.username.data or '' }}">
                </div>
                <div class="form-group">
                    <label for="password">Password&nbsp;&nbsp;&nbsp;</label>
                    <input type="password" class="form-control" name="password" id="password"
                        value="{{ form.password.data or '' }}">
                </div>
                <button type="submit" class="btn btn-primary" style='font-size:20px; color:white; background:rgba(0,0,0,0); border:none; cursor:pointer; display:inline-block;'>Log In</button>

                
            </form>
        </div>
    </body>

Database/Flask project/my_app/templates/my_page.html
<html>
    <head>
    <title>
      My Page
    </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_bootstrap.css') }}">

  
    </head>
    <body>
        {% include "navbar.html" %}
        <div class="jumbotron_mypage">
            <h1 style="font-size:50px; text-align:center; margin-top:50px; color:white;">My Page</h1>

            <h2 class='my_page'>User Name : {{g.user.username}}</h2>

            <h2 class='my_page'>ID : {{g.user.username}}</h2>




            <form method="post" class="post-form">
                {{ form.csrf_token }}
                {% include "form_errors.html" %}

                <div class="form-group">
                    <label for="password">New Password&nbsp;&nbsp;&nbsp;</label>
                    <input type="password" class="form-control" name="password" id="password"
                        value="{{ form.password.data or '' }}">
                </div>
                <button type="submit" class="btn btn-primary" style='font-size:20px; color:white; background:rgba(0,0,0,0); border:none; cursor:pointer; display:inline-block;'>
                    Change Password</button>
            </form>


            <a class="delete btn btn-sm btn-outline-secondary" href="{{ url_for('user.delete', user_id=g.user.username) }}">Delete User</a>

        </div>
    </body>

Database/Flask project/my_app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">


    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="navbar-brand" href="{{ url_for('main.main') }}"><b>Home</b></a>
            </li>
        </ul>
            
        
        {% if g.user %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('user.logout') }}"><b>{{ g.user.username }} (Log out)</b></a>
            </li>


            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('user.mypage') }}"><b>My Page</b></a>
            </li>
        </ul>

        
        {% else %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('user.signup') }}"><b>Sign Up</b></a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('user.login') }}"><b>Log in</b></a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>

Database/Flask project/my_app/templates/product.html
<html>
  <head>
    <title>
      Index Page
    </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/recipe_bootstrap.css') }}">
  </head>

  <body>
    {% include "navbar.html" %}

    <div class="container">
      <div class="jumbotron">
        <h1 style="font-size:40px; text-align:center; margin-top:0;">{{product.title_orig}}</h1>
        <br>
        <h1 style="text-align:center;"><img src="../static/images/sample2.jpg" width=80%> </h1>
        <br>

        <table style='color:white'>
          <thead>
            <tr>
              <th colspan=2 style='font-size:25px;'>Price</th>
              <th> &nbsp;&nbsp;&nbsp;&nbsp;</th> 
              <th colospan=4 style='font-size:20px;'>{{'%-.2f' %product.price|float}}</th>
            </tr>
            <tr><th><br></th></tr>
            <tr>
              <th colspan=2 style='font-size:25px;'>Color </th>
              <th> &nbsp;&nbsp;&nbsp;&nbsp; </th>
              <th colospan=4 style='font-size:20px;'> {{product.product_color}}</th>
            </tr>
            <tr><th><br></th></tr>
            <tr>
              <th colspan=2 style='font-size:25px;'>Shipping Option </th>
              <th> &nbsp;&nbsp;&nbsp;&nbsp; </th>
              <th colospan=4 style='font-size:20px;'> {{product.shipping_option_name}}</th>
            </tr>
            <tr><th><br></th></tr>
            <tr>
              <th colspan=2 style='font-size:25px;'>Shipping Fee</th>
              <th>&nbsp;&nbsp;&nbsp;&nbsp; </th>
              <th colospan=4 style='font-size:20px;'> {{product.shipping_option_price}}</th>
            </tr>
            <tr><th><br></th></tr>
            <tr>
              <th colspan=2 style='font-size:25px;'>Origin </th>
              <th> &nbsp;&nbsp;  &nbsp;&nbsp; </th>
              <th colospan=4 style='font-size:20px;'> {{product.origin_country}}</th>
            </tr>
            <tr><th><br></th></tr>
            <tr>
              <th colspan=2 style='font-size:25px;'>Units Sold </th>
              <th>&nbsp;&nbsp;  &nbsp;&nbsp; </th>
              <th colospan=4 style='font-size:20px;'> {{total_sales}}</th>
            </tr>
            <tr><th><br></th></tr>
            <tr>
              <th colspan=2 style='font-size:25px;'>Rating </th>
              <th> &nbsp;&nbsp;&nbsp;&nbsp; </th>
              <th colospan=4 style='font-size:20px;'> {{'%-.2f' %rating_data.rating|float}}</th>
            </tr>
            <tr><th><br></th></tr>
            <tr>
              <th colspan=2 style='font-size:25px;'>Total Rating Count</th> 
              <th> &nbsp;&nbsp; &nbsp;&nbsp; </th>
              <th colospan=4 style='font-size:20px;'> {{'%-0.f' %rating_count}}</th>
            </tr>
            <tr><th><br></th></tr>
            <tr>
              <th colspan=2 style='font-size:25px;'>Rating 5</th>
              <th> &nbsp;&nbsp; &nbsp;&nbsp; </th>
              <th colospan=4 style='font-size:20px;'> {{'%-0.f' %rating_data.rating_five_count}}</th>
            </tr>
            <tr><th><br></th></tr>
            <tr>
              <th colspan=2 style='font-size:25px;'>Rating 4 </th>
              <th> &nbsp;&nbsp; &nbsp;&nbsp;</th>
              <th colospan=4 style='font-size:20px;'> {{'%-0.f' %rating_data.rating_four_count}}</th>
            </tr>
            <tr><th><br></th></tr>
            <tr>
              <th colspan=2 style='font-size:25px;'>Rating 3 </th>
              <th> &nbsp;&nbsp; &nbsp;&nbsp; </th>
              <th colospan=4 style='font-size:20px;'> {{'%-0.f' %rating_data.rating_three_count}}</th>
            </tr>
            <tr><th><br></th></tr>
            <tr>
              <th colspan=2 style='font-size:25px;'>Rating 2 </th>
              <th> &nbsp;&nbsp; &nbsp;&nbsp; </th>
              <th colospan=4 style='font-size:20px;'> {{'%-0.f' %rating_data.rating_two_count}}</th>
            </tr>
            <tr><th><br></th></tr>
            <tr>
              <th colspan=2 style='font-size:25px;'>Rating 1 </th>
              <th> &nbsp;&nbsp; &nbsp;&nbsp; </th>
              <th colospan=4 style='font-size:20px;'> {{'%-0.f' %rating_data.rating_one_count}}</th>
            </tr>
            <tr><th><br></th></tr>
          </thead>
        </table>
      </div>
    </div>
  </body>
</html>

Database/Flask project/my_app/templates/search.html
<html>
  <head>
    <title>
      Index Page
    </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main_style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/search_bootstrap.css') }}">

  </head>
  <body>
    {% include "navbar.html" %}
   
    <div class="container">
      <div class="jumbotron">
        <h1 style='color:rgb(255, 102, 0)'> Search results for "{{keyword}}"</h1>
        <br>
        
        <br>
        {% for result in results %}
        {% set title = result[0] %}
        {% set rating = result[4] %}
        {% set color = result[2] %}
        {% set origin = result[1] %}
        {% set index = result[5] %}
        {% set price = result[6] %}

          <div class="results"> 
            <div classs="name">
              <h1>
                <a href="{{ url_for('main.product', item_index=index) }}"><span style='color:white'>{{title}}</span></a>
              </h1>
              <a ><b>Price</b> : {{'%-.2f' %price|float}}</a>
              <br>
              <a ><b>Rating</b> : {{'%-.2f' %rating|float}}</a>
              <br>
              <a><b>color</b> : {{color}}</a>
              <br>
              <a><b>origin</b> : {{origin}}</a>
              <br>         
              <br>
              <hr>
              <br>
            </div>
          </div>
        {% endfor %}
        



        <!-- {% for id in ids %}
            {% set item_1 = ids[loop.index-1] %}
            {% set item_2 = counts[loop.index-1] %}
            {% set item_3 = results[loop.index-1][2] %}
            <h1> {{item_1}}, {{item_2}}, {{item_3}}</h1>

        {% endfor %} -->
        

<!-- 

      {% for id in ids %}
        {% for count in counts %}
        {{id, count}} <br>
        {% endfor %}
      {% endfor %} -->


      </div>

    </div>
  </body>
</html>

Database/Flask project/my_app/templates/signup.html
<html>
    <head>
        <title>
            Sign up Page
          </title>
          <link rel="stylesheet" href="{{ url_for('static', filename='css/main_style.css') }}">
          <link rel="stylesheet" href="{{ url_for('static', filename='css/main_bootstrap.css') }}">
    </head>
    <body> 
        {% include "navbar.html" %}
    
        <div class="jumbotron_login">
            <h1 style="font-size:50px; text-align:center; margin-top:50px; color:white;">Sign Up</h1>
            <form method="post" class="post-form">
                {{ form.csrf_token }}
                {% include "form_errors.html" %}
                <div class="form-group">
                    <label for="username">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;User name&nbsp;&nbsp;</label>
                    <input type="text" class="form-control" name="username" id="username"
                        value="{{ form.username.data or '' }}">
                </div>
                <div class="form-group">
                    <label for="password1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Password&nbsp;&nbsp;</label>
                    <input type="password" class="form-control" name="password1" id="password1"
                        value="{{ form.password1.data or '' }}">
                </div>
                <div class="form-group">
                    <label for="password2">Reconfirm password&nbsp;&nbsp;</label>
                    <input type="password" class="form-control" name="password2" id="password2"
                        value="{{ form.password2.data or '' }}">
                </div>
                <button type="submit" class="btn btn-primary" style='font-size:20px; color:white; background:rgba(0,0,0,0); border:none; cursor:pointer; display:inline-block;'>create</button>
            </form>
        </div>
    </body>

Database/Flask project/my_app/templates/test_page.html
<html>
    <head>
        <title>
        Index Page
        </title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main_style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main_bootstrap.css') }}">

    </head>


    <body>
        {% include "navbar.html" %}
        
        <div class='title'>
          <h1 style="font-size:100px; text-align:center; margin-top:50px; color:white;">Test : {{test}}</h1>
        </div>

        <form method="get" action="{{ url_for('main.search', name='kw') }}">
            <div class="input-group" style='font-size: 50px;'>
              <input type="text" class="form-control kw" name="kw" id="kw" value="{{kw or '' }}" placeholder="Enter search value">
              <input type="submit" class="btn btn-primary" style="width:120px;background-color: maroon; border:none; cursor:pointer;" value="Search">
            </div>  
          </form>


    </body>
</html>